### ISSUE TITLE
Dealing with huge number of assets files

### ISSUE THREAD

**Issue by MilosStanic** [Innovic-io/angular-nestjs-rendering#2]
I'm writing an app that uses a huge number of static assets, i.e. .png images. There is almost 6,000 of them.
These assets should be most desireably served from the server only. 
When I run `npm run build:universal` it creates a `/dist` folder with compiled app, however the images, which originally reside in `/src/client/assets/myimages` are copied to both  `/dist/client/assets/myimages` and `/dist/server/assets/myimages`. 
This is a problem because there's about 860MB of images, so now, I have three copies of these images, which amounts to 2.6GB of disk space. 
Also, I can't even run `npm run build:universal` on my production server, because at about 4,500 images it shoots an error: 
```
An error occured during the build:
Error: EMFILE: too many open files, open '/home/<mysite>/<myapp>/dist/client/assets/<myimages>/image-4431.png'
EMFILE: too many open files, open '/home/<mysite>/<myapp>/dist/client/assets/<myimages>/image-4431.png'
Error: EMFILE: too many open files, open '/home/<mysite>/<myapp>/dist/client/assets/<myimages>/image-4431.png'
```

So, now, my questions: 
1. Is it better if I keep these images in `/src/server` folder and somehow serve them as static files?
1a. How do I serve images as static files from server portion of app, and how do I load them from front-end Angular portion of the app?
2. Is it better if I keep these images in `src/shared` folder
2a. How do I load them from shared folder in the Angular portion of the app? 
3. Would any of these strategies reduce the footprint of the compiled app? I.e. would I have two instead of three copies of the image files? 
4. Finally, can the compiler/webpack be told to not consider the image files in the compiling process, and just let me manually copy them at some known destination, so the compiled app would know where to find them?

Thanks.

**Comment by MilosStanic** [comment]
This appears to be a problem with webpack. 
Ref. https://github.com/webpack/webpack/issues/3164

I'm trying to circumvent this problem by deleting the .png files from `/src/client/assets` at build time, and then manually copying them to `/dist/client/assets` after build.

To make the compiler skip the `assets/<myimages>` folder, I used the recipe described here: 
https://github.com/angular/angular-cli/issues/5435#issuecomment-373072287

So this is kind of an extreme example, and can not be treated as issue here. 
But you may leave it here for posterity. 

Thanks.

**Comment by vladotesanovic** [comment]
Ok tnx Milos,

I was going to look at your issue, but if it is fixed and unrelated, even better for me.
